CREATE TABLE contact (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  lastname VARCHAR(20) NOT NULL,
  firstname VARCHAR(20) NOT NULL,
  email VARCHAR(50) NOT NULL,
  subject VARCHAR(30) NOT NULL,
  message TEXT NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_treated BOOLEAN NOT NULL DEFAULT false
);

